cloud:
  aws:
    credentials:
      access-key: AKIAX3DNHQMUAJX4RMOF
      secret-key: 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
    region:
      static: ap-south-1
    stack:
      auto: false

application:
  bucket:
    name: shoppersclouds


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB
